#!/bin/bash

file=${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS[0]}

__notify()
{
    summary=$1
    body=$2
    notify-send --expire-time 200 --app-name "git-get" --category "nautilus" "${summary}" "${body}"
}

remote_url=`git ls-remote --get-url 2>/dev/null`
if [[ x$remote_url == x ]]
then
    __notify "error" "not exist remote: $file"
    exit -1
fi

file_git_path=`git ls-files --full-name $file`
if [[ x$file_git_path == x ]]
then
    __notify "error" "local file not found in remote: $file"
    exit -1
fi

git_branch=$(git rev-parse --abbrev-ref HEAD)

remote_file_exist=`git cat-file -e origin/${git_branch}:${file_git_path} && echo "exist"`
if [[ x$remote_file_exist == x ]]
then
    __notify "error" "remote has no $file"
    exit -1
fi

gitee_repo=${remote_url##*gitee.com}
github_repo=${remote_url##*github.com}

if [[ x$gitee_repo != ${remote_url} ]]
then
    raw_url="https://gitee.com/${gitee_repo:1:-4}/raw/${git_branch}/${file_git_path}"
elif [[ x$github_repo != ${remote_url} ]]
then
    raw_url="https://raw.githubusercontent.com/${github_repo:1:-4}/raw/${git_branch}/${file_git_path}"
else
    __notify "error" "repo url invalid"
    exit -1
fi

__notify "get" "$raw_url"
echo $raw_url | xclip -i -selection primary -filter | xclip -i -selection clipboard
