#!/bin/bash

alias sl='ls'
alias rm='rm -i'
alias sudo='sudo env PATH=$PATH'
alias grep='grep --color=auto --exclude-dir=.svn --exclude-dir=.git --exclude=tags'

xpwd() 
{
    tt=`pwd`
    echo $tt
    export tt
}

alias 0vi='vim --noplugin'
alias vi='vim'
alias xrs='sed -i "s/\s\+$//g" `find . -maxdepth 1 -type f `'

stty stop ''

####### Docker ###########
alias di='docker images'
alias dri='docker rmi' # $(docker images -q)'

alias dc='docker container ls'
alias drc='docker container rm' # $(docker ps -aq)'
alias dsc='docker container stop' #  $(docker ps -aq)'

alias dv='docker volume ls'
alias drv='docker volume rm'

alias dps='docker ps -a'
alias dcup='docker-compose up'

alias dip='docker inspect --format="{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}"'
alias dit='docker exec -it'

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
[ -f ~/.tmp.bash ] && source ~/.tmp.bash
