#!/bin/bash

remote_hostnames=('k8-master' 'k8-storage')
remote_relative_path=('/root/hzcsai_com/hzcsk8s/' '/data/k8s-nfs/codes/hzcsk8s')

cd $(dirname $0)

for (( i=0; i<${#remote_hostnames[@]}; i++ ))
do
    rsync -azcul --exclude ".git" --relative "$2/$3" "${remote_hostnames[$i]}:${remote_relative_path[$i]}"
done

cd -
